POST http://https://node-do-zero-tt5b.onrender.com/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Este é o primeiro vídeo de node",
    "duration": 150
}

###

GET http://https://node-do-zero-tt5b.onrender.com/videos


###

PUT http://https://node-do-zero-tt5b.onrender.com/videos/99301e6a-b3a5-45f0-a4f3-0487546587ce
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Este é o segundo vídeo de Node",
    "duration": 180
}

###

DELETE http://https://node-do-zero-tt5b.onrender.com/videos/f8d2a332-7ca0-468c-9b9d-242d73b33528
