POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Este é o primeiro vídeo de node",
    "duration": 150
}

###

GET http://localhost:3333/videos


###

PUT http://localhost:3333/videos/6089cc53-84d1-4d96-b736-0a7966a83405
Content-Type: application/json

{
    "title": "Video 04",
    "description": "Este é o quarto vídeo de Node",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/f8d2a332-7ca0-468c-9b9d-242d73b33528
